### ISSUE TITLE
In centos7, can't pip install 

### ISSUE THREAD

**Issue by Benny571** [b-2-r/pybfd3#1]
In centos7 install pybfd3, But the prompt was wrong:

pip3 install --user ./pybfd3

Installing collected packages: pybfd3
    Running setup.py install for pybfd3 ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/bfd_xxx/venv_test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-i8pm45bs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-i8pm45bs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-blnho82y/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bfd_xxx/venv_test/include/site/python3.6/pybfd3 --user --prefix=
         cwd: /tmp/pip-req-build-i8pm45bs/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bfd_xxx/venv_test/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-i8pm45bs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-i8pm45bs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-blnho82y/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bfd_xxx/venv_test/include/site/python3.6/pybfd3 --user --prefix= Check the logs for full command output.

**Comment by b-2-r** [comment]
Hi.

Since I don't know your exact environment I cannot say what the problem is.  
Depending on your environment you could try the following:

- upgrade setuptools + wheel ( **pip install -U setuptools && pip install -U wheel**)
- try pip's --egg option --> **pip3 install --user --egg ./pybfd3**
- do a local install via python3 ... or easy_install e.g. **python3 setup.py install --user**
